/**
 * @file cca_coeffs.h
 * @brief CCA Reference Signals and Stimulus Frequencies
 * @author manhdatbn93@gmail.com
 * @date 2025-05-24
 * @version 1.0
 *
 * @note Auto-generated file - DO NOT MODIFY DIRECTLY
 *       This file is generated by cca_gen.py
 *       To make changes, modify the generator script and regenerate
 *
 * Contains pre-computed CCA reference signals and stimulus frequencies
 * for SSVEP detection system with 6 target frequencies and 2 harmonics
 */

#ifndef CCA_COEFFS_H
#define CCA_COEFFS_H

#ifdef __cplusplus
extern "C" {
#endif

/* System Configuration Constants */
#define CCA_SAMPLES         2000  ///< Number of samples per reference signal
#define CCA_SAMPLING_RATE   500   ///< Sampling rate in Hz
#define CCA_NUM_FREQS       6     ///< Number of target stimulus frequencies
#define CCA_HARMONICS       2     ///< Number of harmonics used
#define CCA_NUM_FEATURES   (CCA_HARMONICS * 2)  ///< Features per frequency (sin+cos components)

/**
 * @brief Pre-computed CCA reference signals
 *
 * 3D array structure:
 * [target_frequency][harmonic_component][time_sample]
 *
 * - First dimension: CCA_NUM_FREQS (6 target frequencies)
 * - Second dimension: CCA_NUM_FEATURES (4 components: sin1,cos1,sin2,cos2)
 * - Third dimension: CCA_SAMPLES (2000 time samples)
 *
 * @note Generated for 500Hz sampling rate
 */
extern const float cca_reference_signals[CCA_NUM_FREQS][CCA_NUM_FEATURES][CCA_SAMPLES];

/**
 * @brief Stimulus frequencies table
 *
 * Array of CCA_NUM_FREQS (6) frequencies in Hz that correspond to:
 * - The indices of cca_reference_signals first dimension
 * - The visual stimulus frequencies used in the system
 *
 * @example cca_stim_freqs[0] = frequency of first target
 */
extern const float cca_stim_freqs[CCA_NUM_FREQS];

#ifdef __cplusplus
}
#endif

#endif /* CCA_COEFFS_H */