/**
 * @file filter_coeffs.h
 * @brief Digital Filter Coefficients for EEG Signal Processing
 * @author manhdatbn93@gmail.com
 * @date 2025-05-24
 * @version 1.0
 *
 * @note Auto-generated file - DO NOT MODIFY DIRECTLY
 *       This file is generated by filter_gen.py
 *       To make changes, modify the generator script and regenerate
 *
 * Contains coefficients for 3rd-order Butterworth bandpass filter (2-45Hz)
 * designed for 500Hz sampling rate EEG systems
 */

#ifndef FILTER_COEFFS_H
#define FILTER_COEFFS_H

#ifdef __cplusplus
extern "C" {
#endif

/* Filter Specifications */
#define FILTER_ORDER   7      ///< Filter order (N+1 where N=6 for 3rd-order)
#define LOWCUT         2      ///< Low cutoff frequency (Hz)
#define HIGHCUT        45     ///< High cutoff frequency (Hz)
#define SAMPLING_RATE  500    ///< System sampling rate (Hz)
#define MAX_VALUES     3000   ///< Maximum expected input samples
#define PADLEN         21     ///< Padding length for filtering operations

/**
 * @brief FIR coefficients (feedforward/b coefficients)
 *
 * Array of FILTER_ORDER (7) numerator coefficients for the difference equation:
 * y[n] = b0*x[n] + b1*x[n-1] + ... - a1*y[n-1] - a2*y[n-2] - ...
 *
 * @note These coefficients implement the zero-phase filtering when applied forward
 * and backward (as in filtfilt operations)
 */
const double b_coeffs[FILTER_ORDER] = {
    0.01228905f,
    0.00000000f,
    -0.03686715f,
    0.00000000f,
    0.03686715f,
    0.00000000f,
    -0.01228905f,
};

/**
 * @brief IIR coefficients (feedback/a coefficients)
 *
 * Array of FILTER_ORDER (7) denominator coefficients.
 * First coefficient (a0) is normalized to 1.0.
 *
 * @note These coefficients correspond to a stable filter implementation
 * with poles within the unit circle
 */
const double a_coeffs[FILTER_ORDER] = {
    1.00000000f,
    -4.89452578f,
    10.03520493f,
    -11.06725941f,
    6.94168392f,
    -2.34963940f,
    0.33453752f,
};

/**
 * @brief Initial condition coefficients for filter stability
 *
 * Array of FILTER_ORDER-1 (6) initial conditions that compensate
 * for the filter's transient response.
 *
 * @note These are particularly important for segmented signal processing
 * to maintain continuity between blocks
 */
const double zi_coeffs[FILTER_ORDER - 1] = {
    -0.01228905f,
    -0.01228905f,
    0.02457810f,
    0.02457810f,
    -0.01228905f,
    -0.01228905f,
};

#ifdef __cplusplus
}
#endif

#endif /* FILTER_COEFFS_H */